# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2025, Intel Corporation. All rights reserved.
# Author:Tomasz Ossowski <tomasz.ossowski@intel.com>

top_srcdir	?= ../../../..

include $(top_srcdir)/include/mk/env_pre.mk


INSTALL_TARGETS	:= *.sh ccd-linux-tools/cswitch-control/pyftdi/*

include $(top_srcdir)/include/mk/generic_leaf_target.mk
