# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 Helena Anna Dubel <helena.anna.dubel@intel.com>

top_srcdir		?= ../../..

include $(top_srcdir)/include/mk/env_pre.mk

SUBDIRS			:= datafiles

include $(top_srcdir)/include/mk/testcases.mk
include $(top_srcdir)/include/mk/generic_trunk_target.mk
