# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025-2026 Intel - http://www.intel.com/

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/env_pre.mk

INSTALL_DIR		:= testcases/data/mce
INSTALL_TARGETS	:= mce_test_corrected

include $(top_srcdir)/include/mk/generic_leaf_target.mk
