# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 Helena Anna Dubel <helena.anna.dubel@intel.com>

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/env_pre.mk

INSTALL_DIR		:= testcases/data/mce
INSTALL_TARGETS	:= mce_test_corrected

include $(top_srcdir)/include/mk/generic_leaf_target.mk
